cc_binary(
    name = 'simple_example',
    srcs = [
        'simple_example.cc',
    ],
    deps = [
        '//thirdparty/rocksdb:rocksdb',
    ],
)

cc_binary(
    name = 'column_families_example',
    srcs = [
        'column_families_example.cc',
    ],
    deps = [
        '//thirdparty/rocksdb:rocksdb',
    ],
)

cc_binary(
    name = 'compact_files_example',
    srcs = [
        'compact_files_example.cc',
    ],
    deps = [
        '//thirdparty/rocksdb:rocksdb',
    ],
)

